### ISSUE TITLE
archive.mozilla.org bustage: "Attempt to decode JSON with unexpected mimetype: text/html; charset=utf-8"

### ISSUE THREAD

**Issue by gbrownmozilla** [mozilla/PollBot#381]
Bustage seen on delivery dashboard and in recent unit tests: It looks like all archive.mozilla.org requests are failing.

```
_____________________________ test_nightly_archive _____________________________

cli = <aiohttp.test_utils.TestClient object at 0x7f2ed035ad30>

    async def test_nightly_archive(cli):
        resp = await check_response(cli, "/v1/firefox/58.0a1/archive")
        body = await resp.json()
        assert 'firefox/nightly/latest-mozilla-central-l10n' in body['message']
>       assert body['link'] == ("https://archive.mozilla.org/pub/firefox/nightly/"
                                "latest-mozilla-central-l10n/")
E       KeyError: 'link'

tests/test_views.py:409: KeyError
------------------------------ Captured log call -------------------------------
ERROR    pollbot.views:release.py:23 0, message='Attempt to decode JSON with unexpected mimetype: text/html; charset=utf-8', url=URL('https://archive.mozilla.org/pub/firefox/nightly/latest-mozilla-central-l10n/')
Traceback (most recent call last):
  File "/app/pollbot/views/release.py", line 21, in wrapped
    response = await task(product, version)
  File "/app/pollbot/tasks/archives.py", line 280, in archives
    body = await resp.json()
  File "/tmp/tests/lib/python3.8/site-packages/aiohttp/client_reqrep.py", line 1104, in json
    raise ContentTypeError(
aiohttp.client_exceptions.ContentTypeError: 0, message='Attempt to decode JSON with unexpected mimetype: text/html; charset=utf-8', url=URL('https://archive.mozilla.org/pub/firefox/nightly/latest-mozilla-central-l10n/')
```

**Comment by gbrownmozilla** [comment]
I'm sure this was okay a few weeks ago. Also, I've verified locally that the tests fail the same way even with a build from ~1 year ago. I think there must have been a change to archive.mozilla.org.

**Comment by gbrownmozilla** [comment]
It looks like AMO is returning text/html where it previously returned json. 

For example, a request for ```https://archive.mozilla.org/pub/firefox/nightly/latest-mozilla-central-l10n/``` with request header ```{"Accept": "application/json"}``` now returns text with response header ```'Content-Type': 'text/html; charset=utf-8'```.

**Comment by gbrownmozilla** [comment]
Looking at failed tests in pull requests, I think this behavior changed between Nov 8 2022 and Nov 28 2022.

**Comment by cvalaas** [comment]
s/b fixed in bucketlister code now: https://github.com/mozilla-services/bucketlister-gcs/releases/tag/v1.22.0

**Comment by gbrownmozilla** [comment]
Initially, after the bucketlister changes, some tests were still failing, but now they are all passing. I guess there was still some caching happening and now it's aged out?

Anyway, everything is now working -- thank you very much @cvalaas !!
